routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});
Route::resource('/cars', 'CarsController');

app/Car.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Car extends Model
{
    public $timestamps = false;
    protected $fillable = [        
        'placa',
        'color',
        'fecha_compra',
        'owner_id',
        'status_id'
    ];
    public function owner() {
        return $this->belongsTo('\App\Owner');
      }
      public function status() {
        return $this->belongsTo('\App\Status');
      }
}

app/Owner.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Owner extends Model
{
    protected $fillable = [        
        'dni',
        'name',
        'surname'        
    ];

    public function cars()
	{
	    return $this->hasMany('\App\Car');
	}
  
}

app/Status.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Status extends Model
{
    protected $fillable = [    
        'name'        
    ];

   
}

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
}

app/Http/Controllers/CarsController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class CarsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $cars=\App\Car::all();  
      //  dd($cars->toArray());
        return view('cars.index', compact('cars'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $owners=\App\Owner::all();  
        return view('cars.create', compact('owners'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
      try{
        \DB::beginTransaction();
        \App\Car::create($request->all());
        \DB::commit();
       
      }
    catch (\Exception $ex) {
        \DB::rollback();
        die($ex->getMessage());
    }
    return redirect()->route('cars.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
       return "it works";
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(\App\Car $car)
    {
        
        $owners=\App\Owner::all();
        $status=\App\Status::all();  
        return view('cars.edit', compact('owners','status','car'));
       
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, \App\Car $car)
    {
        
        $car->update($request->all());
        return redirect()->route('cars.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(\App\Car $car)
    {
       
        $car->delete(); 
        return redirect()->route('cars.index');
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

resources/views/cars/create.blade.php
@extends('layout')
@section('content')
<h1>Incluir carro</h1>
        <form action="{{route('cars.store')}}" method="post">
                {{ csrf_field() }}
            <label>Propietario</label>
            <select name="owner_id">
                <option value="0" selected disabled>selecciona un dueño</option>
                @foreach($owners as $owner)
                <option value="{{$owner->id}}">{{$owner->dni.'-'.$owner->name}}</option>
                @endforeach
            </select><br>
            <label>Placa</label>
            <input type="text" name="placa" required><br>
            <label>Color</label>
            <input type="text" name="color" required><br>
            <label>Fecha de Compra</label>
            <input type="date" name="fecha_compra" required><br>
            <button type="submit">guardar</button>
        </form>
@endsection

resources/views/cars/edit.blade.php
@extends('layout')
@section('content')
<h1>Modificar carro</h1>
        <form action="{{route('cars.update',$car->id)}}" method="post">
                {{ method_field('PATCH') }}  
                {{ csrf_field() }}
            <label>Propietario</label>
            <select name="owner_id">
                
                @foreach($owners as $owner)
                @if ($owner->id==$car->owner->id)
                <option value="{{$owner->id}}" selected>{{$owner->dni.'-'.$owner->name}}</option>
                @else
                <option value="{{$owner->id}}">{{$owner->dni.'-'.$owner->name}}</option>
                @endif
                @endforeach
            </select><br>
            <label>Placa</label>
            <input type="text" name="placa" required value="{{$car->placa}}"><br>
            <label>Color</label>
            <input type="text" name="color" required value="{{$car->color}}"><br>
            <label>Fecha de Compra</label>
            <input type="date" name="fecha_compra" required value="{{$car->fecha_compra}}"><br>
            <label>Propietario</label>
            <select name="status_id">
                
                @foreach($status as $statu)
                @if ($statu->id==$car->status_id)
                <option value="{{$statu->id}}" selected>{{$statu->name}}</option>
                @else
                <option value="{{$statu->id}}">{{$statu->name}}</option>
                @endif
                @endforeach
            </select><br>
            <button type="submit">guardar</button>
        </form>
@endsection

resources/views/cars/index.blade.php
            @extends('layout')
            @section('content')

        <h1>Carros</h1>
        <a href="{{route('cars.create')}}">incluir carro</a>
        <table class="table table-striped">
        <tr>
            
               <th><strong> placa</strong></th>
               <th><strong> color</strong></th>
               <th><strong> fecha de compra</strong></th>
               <th><strong> propietario</strong></th>
               <th><strong> status</strong></th>


            @foreach ($cars as $car)                
<tr>
                   <td> {{ $car->placa }} </td>
                   <td> {{ $car->color }} </td>
                   <td> {{ $car->fecha_compra }} </td>
                   <td> {{ $car->owner->name }} </td>
                   <td> {{ $car->status->name }} </td>
                   <td><a href="{{route('cars.edit',$car->id)}}">modificar</a></td>
                   <td>
                    <form id="delete-form" action="{{ route('cars.destroy',$car->id) }}" method="POST" >
                            {{ method_field('DELETE') }} 
                            {{ csrf_field() }}
                            <button type="submit">Eliminar</button>
                          </form>
                </td>
</tr>

            @endforeach
        </tr>
        </table
   @endsection

resources/views/layout.blade.php
<!doctype html>
<html lang="{{ app()->getLocale() }}">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <title>Laravel</title>

        <!-- Fonts -->
        <link href="https://fonts.googleapis.com/css?family=Nunito:200,600" rel="stylesheet" type="text/css">

        <!-- Styles -->
        <style>
            html, body {
                background-color: #fff;
                color: #636b6f;
                font-family: 'Nunito', sans-serif;
                font-weight: 200;
                height: 100vh;
                margin: 0;
            }

            .full-height {
                height: 100vh;
            }

            .flex-center {
                align-items: center;
                display: flex;
                justify-content: center;
            }

            .position-ref {
                position: relative;
            }

            .top-right {
                position: absolute;
                right: 10px;
                top: 18px;
            }

            .content {
                text-align: center;
            }

            .title {
                font-size: 84px;
            }

            .links > a {
                color: #636b6f;
                padding: 0 25px;
                font-size: 12px;
                font-weight: 600;
                letter-spacing: .1rem;
                text-decoration: none;
                text-transform: uppercase;
            }

            .m-b-md {
                margin-bottom: 30px;
            }
        </style>
    </head>
    <body>
      @yield('content')
    </body>
</html>